export const STORE_DELIVERY_REPOSITORY = 'STORE_DELIVERY_REPOSITORY';
export const CREDIT_NOTE_REPOSITORY = 'CREDIT_NOTE_REPOSITORY';
export const TRIP_LIQUIDATION_REPOSITORY = 'TRIP_LIQUIDATION_REPOSITORY';
