export enum TripEvent {
  CREATED = 'CREATED',
  STARTED = 'STARTED',
  LOCATION_UPDATE = 'LOCATION_UPDATE',
  STOP_ARRIVED = 'STOP_ARRIVED',
  STOP_COMPLETED = 'STOP_COMPLETED',
  CHECKLIST_VERIFIED = 'CHECKLIST_VERIFIED',
  DELAY_REPORTED = 'DELAY_REPORTED',
  INCIDENT = 'INCIDENT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
